name: news_app
description: A Flutter news application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.14
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_animate:
  dio: ^5.4.1
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  adaptive_icon_background: "#212529"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/